### PR TITLE
Development v1.1.8 merge to master

### PR DESCRIPTION
**Pull request by SV-Zanshin**
# Description
Corrected a bug in the battery backup mode and cleaned up formatting using clang-format

Fixes # (issue)
Issue #49 - battery backup error
Issue #50 - clang-formatting
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested
- [ ] Test for regression
- [ ] Test for corrected functionality

**Test Configuration**:
* Arduino version: 1.8.13
* Arduino Hardware: Uno, Micro
* SDK: Visual Studio with Visual-Micro

# Checklist:

- [x] The changes made link back to an existing issue number
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation / Wiki Page(s)
- [x] My changes generate no new warnings
- [x] I have checked potential areas where regression errors could occur and have found no issues
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Zanshin Logo

### CODE REVIEW

**Comment by manaioussema** [comment]
Thank you for your great work @SV-Zanshin . I tried the new version and yes it is working, but sometimes the code hangs as the first time.

**Comment by SV-Zanshin** [comment]
What is important, I found, is that the 2 pull-up resistors to the I2C bus remain powered; initially I had them on the board with the MCP7940 and when I removed power then the I2C bus got hung up. I think that might be what is happening to you as well.

**Comment by manaioussema** [comment]
if that is the case why sometimes it works sometimes it doesn't?

**Comment by SV-Zanshin** [comment]
Without a pullup the state is undefined.  There are numerous threads on the web about sporadic/indeterminate I2C behaviour without pull-ups.

 

When I shifted my pull-up resistors to the Arduino board and kept them to +5V (Arduino UNO and Micro test boards) and had my MCP7940N hooked up to 3.3V on the battery backup and then removed power to the MCP7940N then I got the expected results.

**Comment by manaioussema** [comment]
leaving the breakout aside, in real life scenario the power will be removed from the hole board (the one that i intend to use the RTC in), and therefore the I2C pull-ups will lose power.

**Comment by SV-Zanshin** [comment]
Yes, that is true and is not a problem, as the clock will resume working once power is re-applied.

 

But the demonstration program is different, it is designed to check the MCP7940 using I2C and thus the pull-ups need to be powered otherwise it can “hang”; and when it restarts it also set the clock. It is not designed as a solution for battery backup issues, but as a demonstration as to how the battery backup functions can be used.

**Comment by manaioussema** [comment]
i see what you mean, however i soldered the pull-ups to the VBAT pin and put a 3.3V to that pin then i disconnected the power from VCC and i still get the to "hang".

**Comment by manaioussema** [comment]
After soldering back the pull-ups to VCC and putting the back the VBAT pin to the coin cell, i modified the code to not check periodically for the power loss and deleted the adjust in the setup, i kept plugging and unplugging the board from the usb and i quite got what would be the real-life scenario.
As you said, the power being applied back will start the oscillator and get everything working back. I truly thank you for your help, wish you all the best.
By the way, can you tell me what is the modification that you made in the library?

**Comment by SV-Zanshin** [comment]
I changed the error handling for I2C around a bit so that it wouldn't reset the MCP7940; you can compare the 2 versions in GIT to get the exact changes made.

**Comment by manaioussema** [comment]
i see, thank you.

**Pull request merged**
