### PR TITLE
Bug fixes - alarm setting

### PR DESCRIPTION
**Pull request by wvmarle**
Found issues with setting the alarms (see also http://forum.arduino.cc/index.php?topic=556111), fixed it.

Git does believe some of your later additions are deleted by me, I don't really understand git so you'll have to be careful when merging.

Lots of enhancements on layout for readability as well.

### CODE REVIEW

**Comment by SV-Zanshin** [comment]
Hello wvmarle,

 

Thanks for putting all that work into finding and fixing library errors! I think part of the issue with all the differences between the main branch and the merge is that I modified the main branch after the fork that you used to make the corrections. Thus if I pull your changes into the main branch I’d lose the changes that I made. Since this is a standard type of issue with source control systems I’m sure that git has some sort of mechanism to handle this. But I’m no git guru so it may take a bit to get that done but your fixed will be integrated even if I have to type them in myself.

 

Thanks,

 

-Arnd.

**Comment by SV-Zanshin** [comment]
It looks like the best way forward is to merge your modifications and enhancements and then I will add my changes which seem to predate your fork but weren't included. One is adding multiple I2C speed capability to the library and the other is a bug fix related to the base day-of-week.

**Comment by SV-Zanshin** [comment]
wvmarle - I see that you are making further enhancements and changes to your forked copy. Please remember to do a "pull" from the master so that the changes that I've incorporated to the master branch are loaded into your copy, then you can put in a pull request so your changes can be integrated back into the master. If you don't do that, then the copies would become out of sync.

**Comment by wvmarle** [comment]
Yes... done that already, got the I2C things.
Another big pull is coming soon for you. Lots of enhancements - reduced my compiled size by some 100 bytes and using just part of the available.
Still testing a few things to make sure everything works.
After that it's time to implement the NVRAM part, and go through the data sheet to make sure complete functionality is there.

**Pull request merged**
